config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  
  get 'static_pages/home'

  get 'static_pages/about'

  resources :sessions, only:[:new, :create, :destroy]
  resources :users
  resources :games

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  		redirect_to users_path
  	end
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="index about">
	<div class="shadows">
		<h2>The Picture Game was built by <a href="http://www.jordanrust.tech">Jordan Rust</a> as a project for the Web Development Immersive Course at General Assembly. This project challenged students to build their first Full-Stack application using the Rails framework.</h2>
	</div>
	<h4>Technologies include:</h4>
	<ul>
	  <li><a href="https://www.ruby-lang.org/">Ruby</a></li>
	  <li><a href="http://rubyonrails.org/">Rails</a></li>
	  <li><a href="http://www.postgresql.org/">PostgreSQL</a></li>
	  <li><a href="http://lesscss.org/">LESS</a></li>
	  <li><a href="http://qrohlf.com/trianglify/">Trianglify</a></li>
	  <li><a href="https://github.com/NyxHemera/canvas-actual">CanvasActual</a></li>
	  <li><a href="https://github.com/NyxHemera/apheleia.css">Apheleia.css</a></li>
	</ul>

	<a class="btn btn-accent" href="http://www.jordanrust.tech">View my Full Portfolio</a>

</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Picture Game - Home') %>
<div class="home-wrap">
  <img src="/logo-lg.png" class="logo-lg">
  <br/>
  <div>
	  <button class="btn btn-accent shadows"><%= link_to 'Sign-Up', signup_path %></button>
	  <button class="btn btn-accent shadows"><%= link_to 'Sign-In', signin_path %></button>
  </div>

  <h3 onclick="togOverlay()">More Info</h3>
</div>

<div class="overlay-wrap" onclick="togOverlay()">
	<div class="overlay-text-wrap shadows" onclick="">
		<h2>What is The Picture Game?</h2>
		<p>The Picture Game is very similar to the telephone game you used to play as a kid. The first player writes a short, 1-2 sentence story. The second player reads that story and draws a picture of the events in that story. After that, the third player can only see the drawing, and must write what they think the story should be. The players alternate from stories to drawings until the game is done.</p>
	</div>
</div>

<script type="text/javascript">
	var overlay = false;
	function togOverlay() {
		console.log("test");
		if(overlay) {
			$('.overlay-wrap').css('opacity', '0');
			setTimeout(function() {
				$('.overlay-wrap').css('visibility', 'hidden');
			}, 510);
			$('.home-wrap').removeClass('blurred');	
		}else {
			$('.overlay-wrap').css('visibility', 'visible');
			$('.overlay-wrap').css('opacity', '100');
			$('.home-wrap').addClass('blurred');
		}
		overlay = !overlay;
	}
	function checkOver() {
		overlay ? togOverlay() : "";
	}
	$(document).on('keydown keypress',function(e) {
		if(e.keyCode == 27) {
			overlay = true;
			togOverlay();
		}
	});
</script>

<style type="text/css">
	.logo-sm {
		display: none;
	}
</style>