config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  
  get 'static_pages/home'

  get 'static_pages/about'

  resources :sessions, only:[:new, :create, :destroy]
  resources :users
  resources :games

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :signed_in_user

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
#    respond_to do |format|
#      format.html
#      format.json { render json: @game }
#    end
  end

  def new
    @game = Game.new
  end

  def edit
    @game = Game.find(params[:id])
    @played = false
    @game.users.each do |user|
      if current_user == user
        @played = true
      end
    end
  end

  def create
    @game = Game.new(game_params)
    @game.users.push(current_user)
    @game.stories.push(params[:game][:stories])
    @game.num_rounds = params[:game][:num_rounds]
    @game.text_last = !@game.text_last
    current_user.games_created += 1;
    current_user.save(validate: false)
    respond_to do |format|
      if @game.save(validate: false)
        format.html { redirect_to games_path, notice: 'Welcome!' }
        #format.json { render :show, status: :created, location: @game }
      else
        format.html { redirect_to new_game_path }
        #format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @game = Game.find(params[:id])
    @game.users.push(current_user)
    if @game.text_last
      @game.draw_urls.push(params[:game][:image])
    else
      @game.stories.push(params[:game][:stories])
    end
    @game.text_last = !@game.text_last

    if @game.num_rounds <= (@game.stories.length + @game.draw_urls.length)
      @game.finished = true
      @game.users.each do |user|
        user.games_completed += 1
        user.save
      end
    end
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to games_path, notice: 'Game was successfully updated.' }
        #format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        #format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      #format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(
        :stories,
        :draw_urls,
        :num_rounds)
    end
end

app/views/games/_gamelistitem.html.erb
<% if game.finished == true %>
<div class="game-li-wrap shadows f-game">
<% else %>
<div class="game-li-wrap shadows ip-game">
<% end %>
		<ul class="photolist">
			<% game.users.each do |user| %>
					<% if user.avatar_file_name != nil %>
						<li><a href=<%= user_path(user) %>><img class="shadows" src=<%= user.avatar.url(:square) %> > </a></li>
					<% else %>
						<li><a href=<%= user_path(user) %>><img class="shadows" src=<%= user.photo_url %> > </a></li>
					<% end %>
			<% end %>
		</ul>
		<h5>Next Move: <%= game.text_last ? "Drawing" : "Text" %></h5>
		<% if !game.finished %>
			<h4>Turn <%= game.stories.length + game.draw_urls.length %></h4>

			<h4>Turns Left: <%= game.num_rounds - (game.stories.length + game.draw_urls.length) %></h4>
		<% else %>
			<h4>Finished!</h4>
		<% end %>
	<% if game.finished %>
		<%= link_to 'View', game_path(game), class: 'btn-clear btn-accent shadows' %>
	<% else %>
		<%= link_to 'Play', edit_game_path(game), class: 'btn-clear btn-accent shadows' %>
	<% end %>
</div>

app/views/games/_imggameform.html.erb
<%= form_for @game, :html => {class: 'form-fixed'} do |f| %>
    <input name="game[image]" type="hidden" id='game_image' value="Random text goes here." />
		<h3 class="text-title-game">Draw an image representing the text above.</h3>
		<input type="submit" name="commit" value="Update Game" onclick="setImageVal()" class="btn btn-accent shadows" />
<% end %>

app/views/games/_textgameform.html.erb
<%= form_for @game, :html => {class: 'form-fixed'} do |f| %>
    <label class="" for="game_story"></label>
    <% if @game.stories.length == 0 %>
    	<div class="tooltip">
		    <textarea class="inp-text inp-text-accent shadows" type="text" value="" name="game[stories]" id="game_story" ></textarea>
		    <span class="tooltiptext tt-right">Write 1-2 sentences to start the game.</span>
	    </div>
    <% else %>
    	<div class="tooltip">
		    <textarea class="inp-text inp-text-accent shadows" type="text" value="" name="game[stories]" id="game_story" ></textarea>
		    <span class="tooltiptext tt-right">Write 1-2 sentences describing the picture above.</span>
	    </div>
    <% end %>    

    <% if @game.stories.length == 0 %>
    	<label class="" for="game_num_rounds">Total Turns: </label>
    	<input class="inp-text inp-text-accent shadows" type="number" value="4" name="game[num_rounds]" id="game_num_rounds" min="4" max="12" />
    	<input type="submit" name="commit" value="Create Game" class="btn btn-accent shadows" />
    <% else %>
    	<input type="submit" name="commit" value="Update Game" class="btn btn-accent shadows" />
    <% end %>
    
<% end %>

app/views/games/edit.html.erb
<% if @played %>
	<div class="index">
		<h3 class="text-title-game">This game is still in progress!</h3>
		<h3 class="text-signin">You should start a new one!</h3>
		<%= link_to "New Game", new_game_path, class: 'btn btn-accent shadows' %>
	</div>
<% else %>
	<div class="index">
		<% if @game.finished %>
			<% redirect_to game_path(@game) %>
		<% end %>

		<% if @game.text_last %>
			<h3 class="text-title-game"><%= @game.stories.last %></h3>
			<div id="canvas-wrap"></div>
	    <script>
				$(document).ready(function() { 
					CA = new CanvasActual();
				});
			</script>
			<%= render 'imggameform' %>
		<% else %>
			<img src=<%= @game.draw_urls.last %> class='shadows'>
			<%= render 'textgameform' %>
		<% end %>
	</div>
<% end %>

app/views/games/index.html.erb
<div class="index">
	<div class="btn-group game-group">
		<button class="btn btn-accent" onclick="showIPG()">In-Progress</button>
		<button class="btn btn-accent" onclick="showAllG()">All Games</button>
		<button class="btn btn-accent" onclick="showCG()">Completed</button>
	</div>
	<% @games.each do |game| %>
		<%= render "gamelistitem", :game => game %>
	<% end %>
	<% if @games.length == 0 %>
		<h3>There are no games in progress!</h3>
		<h3>You should start one!</h3>
		<%= link_to "New Game", new_game_path, class: 'btn btn-accent shadows' %>
	<% end %>
</div>

<script type="text/javascript">

	$('.f-game').hide(300);

</script>

app/views/games/new.html.erb
<div class="index">
	<h2 class="text-title-game">Let's start with a story:</h2>
	<%= render 'textgameform' %>
</div>

app/views/games/show.html.erb
<div class="index show">
	<% j = 0 %>
  <% for i in 0..@game.stories.length-1 %>

  	<a href=<%= user_path(@game.users[j]) %>><img class="shadows" src=<%= @game.users[j].photo_url %> ></a>
  	<% j+=1 %>
    <h3><%= @game.stories[i] %></h3>

    <% if i < @game.draw_urls.length %>

    	<a href=<%= user_path(@game.users[j]) %>><img class="shadows showusr" src=<%= @game.users[j].photo_url %> ></a>
    	<% j+=1 %>
    	<div class="cell">
      <img src=<%= @game.draw_urls[i] %> class='shadows'>
    	</div>

    <% end %>
  <% end %>
</div>