config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  
  get 'static_pages/home'

  get 'static_pages/about'

  resources :sessions, only:[:new, :create, :destroy]
  resources :users
  resources :games

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PictureGame</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
</head>
<body>

<img src="/logo-sm.png" class='logo-sm'>

<% if signed_in? %>
<div class="wrap">
<input type="checkbox" id="nav-trigger" class="nav-trigger" />
<label for="nav-trigger">
	<span></span>
	<span></span>
	<span></span>
	<span></span>
</label>

<ul class="dropdownnav shadows">
	<li><%= link_to 'My Profile', user_path(current_user) %></li>
	<li><%= link_to 'All Users', users_path %></li>
	<li><%= link_to 'All Games', games_path %></li>
  <li><%= link_to 'About', static_pages_about_path %></li>
	<li><a class='btn-clear btn-create shadows' href=<%= new_game_path %>>New Game</a></li>
	<li><%= link_to 'Sign Out',  signout_path, :method => :delete, class: 'btn-clear btn-destroy shadows' %></li>
</ul>
</div>
<% end %>

<%= yield %>

<script>
  function reloadBG() {
    var width = $(document).width();
    var height = $(document).height();
    if(height < screen.height) {
      height = screen.height;
    }

    if(width < screen.width) {
      width = screen.width;
    }
    var pattern = Trianglify({
        width: width*1.2,
        height: height*1.2,
        x_colors: ['#0097A7', '#00BCD4', '#B2EBF2', '#FFFFFF']
    });
    $('body').css('background-image', 'url(' + pattern.png() + ')');
  }
  reloadBG();
</script>

</body>
</html>